options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker' #pre-built image oleh google
    args: ['build', '-t', 
           'gcr.io/b-508911/fastapi-app:latest', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/b-508911/fastapi-app:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'fast-api-test', '--image', 'gcr.io/b-508911/fastapi-app:latest',
           '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/b-508911/fastapi-app:latest'
